#%RAML 1.0
title: User Data Service
baseUri: https://veg-user-data-service-prod.herokuapp.com/
version: v1

/api/users:
  get:

/api/users/register:
  post:

/api/users/login:
  post:

/api/users/logout:
  get:

/api/users/auth:
  get: